### ISSUE TITLE
Missing dependency in package.json

### ISSUE THREAD

**Issue by heikomat** [5minds/addict-ioc#53]
the `utils.ts` uses bluebird, but bluebird isn't listed in addict-iocs dependencies

**Comment by 5ebastianMeier** [comment]
fixed by https://github.com/5minds/addict-ioc/commit/5d8a9268716838d9c1ce6458f37e5626edaaee35

**Comment by heikomat** [comment]
This is not really fixed, because 5d8a926 only adds bluebird as dev-dependency, not as a general dependency @5ebastianMeier
